
set_property PACKAGE_PIN U22 [get_ports PHY_TX_CLK]
set_property IOSTANDARD HSTL_I_18 [get_ports PHY_TX_CLK]
set_property PACKAGE_PIN U21 [get_ports PHY_RX_CLK]
set_property IOSTANDARD HSTL_I_18 [get_ports PHY_RX_CLK]
set_property PACKAGE_PIN V18 [get_ports PHY_RESET_B]
set_property IOSTANDARD LVCMOS18 [get_ports PHY_RESET_B]
set_property PACKAGE_PIN U14 [get_ports PHY_RX_CTRL]
set_property IOSTANDARD HSTL_I_18 [get_ports PHY_RX_CTRL]
set_property PACKAGE_PIN V14 [get_ports {PHY_RXD[3]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {PHY_RXD[3]}]
set_property PACKAGE_PIN V16 [get_ports {PHY_RXD[2]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {PHY_RXD[2]}]
set_property PACKAGE_PIN V17 [get_ports {PHY_RXD[1]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {PHY_RXD[1]}]
set_property PACKAGE_PIN U17 [get_ports {PHY_RXD[0]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {PHY_RXD[0]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PHY_RX_CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {rx_data_out[0]} {rx_data_out[1]} {rx_data_out[2]} {rx_data_out[3]} {rx_data_out[4]} {rx_data_out[5]} {rx_data_out[6]} {rx_data_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 22 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {status[0]} {status[1]} {status[2]} {status[3]} {status[4]} {status[5]} {status[6]} {status[7]} {status[8]} {status[9]} {status[10]} {status[11]} {status[12]} {status[13]} {status[14]} {status[15]} {status[16]} {status[17]} {status[18]} {status[19]} {status[20]} {status[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list byte_rxdv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list data_out_valid]]

set_property MARK_DEBUG true [get_nets {PHY_RXD_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {PHY_RXD_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {PHY_RXD_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {PHY_RXD_IBUF[2]}]
set_property MARK_DEBUG true [get_nets PHY_RX_CTRL_IBUF]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets PHY_RX_CLK_IBUF_BUFG]
