# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xci
# IP: The module: 'pll_25MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xci
# IP: The module: 'pll_25MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_source/ip/pll_25MHZ/pll_25MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
